services:
  node1:
    build: .
    command: "null-db --roster=node1:3001,node2:3002,node3:3003 --id=node1:3001 --encoding=json"
    environment:
      - RUST_LOG=info
    ports:
      - 3001:3001
      - 30001:8080
    volumes:
      - ./node1:/db

  node2:
    build: .
    command: "null-db --roster=node1:3001,node2:3002,node3:3003 --id=node2:3002 --encoding=json"
    environment:
      - RUST_LOG=info
    ports:
      - 3002:3002
      - 30002:8080
    volumes:
      - ./node2:/db

  node3:
    build: .
    command: "null-db --roster=node1:3001,node2:3002,node3:3003 --id=node3:3003 --encoding=json"
    environment:
      - RUST_LOG=info
    ports:
      - 3003:3003
      - 30003:8080
    volumes:
      - ./node3:/db
    develop:
